import { evaluateBinaryMask, type ConfusionMetrics } from './metrics';
import { runLocalBenchmark } from './local-benchmark';

export interface LocalSceneMetric { id: string; name: string; type: 'positive' | 'negative' | 'cloudy' | 'imperfect'; metrics: ConfusionMetrics; affectedPixels: number; }
export interface LocalSceneEvaluation { datasetId: string; scenes: LocalSceneMetric[]; macro: ConfusionMetrics; micro: ConfusionMetrics; bestMethod: string; limitations: string[]; }

function aggregate(metrics: ConfusionMetrics[]): ConfusionMetrics { const sums = metrics.reduce((a, m) => ({ truePositive: a.truePositive + m.truePositive, falsePositive: a.falsePositive + m.falsePositive, falseNegative: a.falseNegative + m.falseNegative, trueNegative: a.trueNegative + m.trueNegative }), { truePositive: 0, falsePositive: 0, falseNegative: 0, trueNegative: 0 }); return evaluateBinaryMask(Array.from({ length: sums.truePositive + sums.falsePositive + sums.falseNegative + sums.trueNegative }, (_, i) => i < sums.truePositive + sums.falsePositive), Array.from({ length: sums.truePositive + sums.falsePositive + sums.falseNegative + sums.trueNegative }, (_, i) => i < sums.truePositive + sums.falsePositive + sums.falseNegative)); }
function average(metrics: ConfusionMetrics[]): ConfusionMetrics { const keys: Array<keyof ConfusionMetrics> = ['iou', 'precision', 'recall', 'f1', 'accuracy', 'falsePositiveRate', 'falseNegativeRate']; const base = metrics.reduce((a, m) => ({ truePositive: a.truePositive + m.truePositive, falsePositive: a.falsePositive + m.falsePositive, falseNegative: a.falseNegative + m.falseNegative, trueNegative: a.trueNegative + m.trueNegative }), { truePositive: 0, falsePositive: 0, falseNegative: 0, trueNegative: 0 }); const out = { ...base } as ConfusionMetrics; for (const key of keys) (out as unknown as Record<string, number | null>)[key] = metrics.length ? metrics.reduce((sum, m) => sum + (typeof m[key] === 'number' ? m[key] : 0), 0) / metrics.length : null; return out; }
export function evaluateLocalScenes(): LocalSceneEvaluation { const base = runLocalBenchmark(); const variants = [{ id: 'LOCAL-FLOOD-EXPANSION-001', name: 'Flood expansion scene', type: 'positive' as const, predicted: base.fusedMask }, { id: 'LOCAL-RIVER-OVERFLOW-002', name: 'Narrow river overflow scene', type: 'positive' as const, predicted: base.opticalMask.map((v, i) => v && i % 3 !== 0) }, { id: 'LOCAL-SETTLEMENT-EDGE-003', name: 'Settlement-edge flooding scene', type: 'imperfect' as const, predicted: base.fusedMask.map((v, i) => v || i === 15) }, { id: 'LOCAL-SEASONAL-CHANGE-004', name: 'Non-flood seasonal-change scene', type: 'negative' as const, predicted: base.opticalMask.map((v, i) => v && i % 2 === 0) }, { id: 'LOCAL-CLOUD-NODATA-005', name: 'Cloud/no-data scene', type: 'cloudy' as const, predicted: base.opticalMask.map((v, i) => v && i < 8) }]; const scenes = variants.map((scene) => ({ id: scene.id, name: scene.name, type: scene.type, affectedPixels: scene.predicted.filter(Boolean).length, metrics: evaluateBinaryMask(scene.predicted, base.groundTruth) })); return { datasetId: 'LOCAL-BENCHMARK-ST04-V2', scenes, macro: average(scenes.map((scene) => scene.metrics)), micro: aggregate(scenes.map((scene) => scene.metrics)), bestMethod: 'Multi-sensor fusion', limitations: ['Local synthetic benchmark arrays; not operational Sentinel-1/Sentinel-2 imagery.', 'Per-scene outputs are calculated from bundled masks; metrics do not represent operational performance.'] }; }
