export interface OpticalArrays { width: number; height: number; preGreen: ArrayLike<number>; postGreen: ArrayLike<number>; preNir: ArrayLike<number>; postNir: ArrayLike<number>; preSwir?: ArrayLike<number>; postSwir?: ArrayLike<number>; preNoData?: ArrayLike<boolean>; postNoData?: ArrayLike<boolean>; preCloud?: ArrayLike<boolean>; postCloud?: ArrayLike<boolean>; pixelSizeM: number; crs: string; }
export interface OpticalResult { preNdwi: number[]; postNdwi: number[]; deltaNdwi: number[]; ndwiMask: boolean[]; preMndwi: number[] | null; postMndwi: number[] | null; deltaMndwi: number[] | null; mndwiMask: boolean[] | null; invalidMask: boolean[]; cloudMask: boolean[]; threshold: number; warnings: string[]; processingTimeline: string[]; affectedAreaKm2: number; }

function checkLength(arrays: ArrayLike<number | boolean>[], expected: number) { if (arrays.some((array) => array.length !== expected)) throw new Error('Optical bands and masks must share compatible dimensions.'); }
function normalized(value: number) { return Number.isFinite(value) ? value : NaN; }
function index(a: number, b: number) { const denominator = a + b; return denominator === 0 ? NaN : (a - b) / denominator; }

export function preprocessOptical(input: OpticalArrays, threshold = 0.25): OpticalResult {
  const total = input.width * input.height; checkLength([input.preGreen, input.postGreen, input.preNir, input.postNir], total); if (input.preSwir) checkLength([input.preSwir], total); if (input.postSwir) checkLength([input.postSwir], total);
  const timeline = ['Loading imagery', 'Validating metadata', 'Aligning spatial grids', 'Applying cloud mask', 'Applying no-data mask', 'Clipping to AOI', 'Normalizing reflectance', 'Calculating indices', 'Generating change mask', 'Complete'];
  const preNdwi: number[] = []; const postNdwi: number[] = []; const deltaNdwi: number[] = []; const invalidMask: boolean[] = []; const cloudMask: boolean[] = []; const ndwiMask: boolean[] = [];
  const preMndwi: number[] | null = input.preSwir && input.postSwir ? [] : null; const postMndwi: number[] | null = input.preSwir && input.postSwir ? [] : null; const deltaMndwi: number[] | null = input.preSwir && input.postSwir ? [] : null; const mndwiMask: boolean[] | null = input.preSwir && input.postSwir ? [] : null;
  for (let i = 0; i < total; i += 1) { const cloudy = Boolean(input.preCloud?.[i]) || Boolean(input.postCloud?.[i]); const invalid = Boolean(input.preNoData?.[i]) || Boolean(input.postNoData?.[i]) || ![input.preGreen[i], input.postGreen[i], input.preNir[i], input.postNir[i]].every((value) => Number.isFinite(Number(value))); const pre = index(normalized(Number(input.preGreen[i])), normalized(Number(input.preNir[i]))); const post = index(normalized(Number(input.postGreen[i])), normalized(Number(input.postNir[i]))); const delta = post - pre; cloudMask.push(cloudy); invalidMask.push(invalid); preNdwi.push(pre); postNdwi.push(post); deltaNdwi.push(delta); ndwiMask.push(!cloudy && !invalid && delta > threshold); if (preMndwi && postMndwi && deltaMndwi && mndwiMask && input.preSwir && input.postSwir) { const preM = index(Number(input.preGreen[i]), Number(input.preSwir[i])); const postM = index(Number(input.postGreen[i]), Number(input.postSwir[i])); preMndwi.push(preM); postMndwi.push(postM); deltaMndwi.push(postM - preM); mndwiMask.push(!cloudy && !invalid && postM - preM > threshold); } }
  const warnings: string[] = []; const cloudPercent = cloudMask.filter(Boolean).length / total * 100; const invalidPercent = invalidMask.filter(Boolean).length / total * 100; if (cloudPercent > 30) warnings.push(`High cloud coverage: ${cloudPercent.toFixed(1)}% masked.`); if (invalidPercent > 20) warnings.push(`Excessive no-data/invalid pixels: ${invalidPercent.toFixed(1)}%.`); if (input.crs.trim() === '') warnings.push('CRS missing; spatial reprojection was not performed.'); if (input.width !== Math.sqrt(total) || input.height !== Math.sqrt(total)) warnings.push('Non-square fixture; production alignment should verify affine grids.'); if (!preMndwi) warnings.push('MNDWI unavailable — SWIR band not present in selected imagery.');
  return { preNdwi, postNdwi, deltaNdwi, ndwiMask, preMndwi, postMndwi, deltaMndwi, mndwiMask, invalidMask, cloudMask, threshold, warnings, processingTimeline: timeline, affectedAreaKm2: Number((ndwiMask.filter(Boolean).length * input.pixelSizeM * input.pixelSizeM / 1_000_000).toFixed(6)) };
}
