export interface PixelDifferenceInput { bands: Array<{ name: string; pre: ArrayLike<number>; post: ArrayLike<number> }>; width: number; height: number; threshold: number; pixelSizeM: number; noData?: ArrayLike<boolean>; cloud?: ArrayLike<boolean>; }
export interface PixelDifferenceResult { values: number[]; rawMask: boolean[]; cleanedMask: boolean[]; uncertaintyMask: boolean[]; noDataMask: boolean[]; cloudMask: boolean[]; threshold: number; bandsUsed: string[]; meanChange: number; maximumChange: number; changedPixelCount: number; rawChangedPixelCount: number; removedNoisePixels: number; changedPixelPercentage: number; affectedAreaM2: number; affectedAreaKm2: number; minimumComponentSize: number; }

export function runPixelDifference(input: PixelDifferenceInput, minimumComponentSize = 2): PixelDifferenceResult {
  const total = input.width * input.height; if (!input.bands.length) throw new Error('At least one common band is required for pixel difference.'); if (input.bands.some((band) => band.pre.length !== total || band.post.length !== total)) throw new Error('Pixel-difference bands must share compatible dimensions.');
  const values = Array.from({ length: total }, (_, i) => { const available = input.bands.map((band) => Math.abs(Number(band.post[i]) - Number(band.pre[i]))).filter(Number.isFinite); return available.length ? available.reduce((a, b) => a + b, 0) / available.length : NaN; });
  const noDataMask = Array.from({ length: total }, (_, i) => Boolean(input.noData?.[i]) || !Number.isFinite(values[i])); const cloudMask = Array.from({ length: total }, (_, i) => Boolean(input.cloud?.[i])); const rawMask = values.map((value, i) => !noDataMask[i] && !cloudMask[i] && value > input.threshold); const cleanedMask = rawMask.slice();
  for (let y = 0; y < input.height; y += 1) for (let x = 0; x < input.width; x += 1) { const i = y * input.width + x; if (!rawMask[i]) continue; let neighbours = 0; for (const [dx, dy] of [[-1,0],[1,0],[0,-1],[0,1]]) { const nx = x + dx; const ny = y + dy; if (nx >= 0 && nx < input.width && ny >= 0 && ny < input.height && rawMask[ny * input.width + nx]) neighbours += 1; } if (neighbours < minimumComponentSize - 1) cleanedMask[i] = false; }
  const validValues = values.filter((value, i) => Number.isFinite(value) && !noDataMask[i]); const changedPixelCount = cleanedMask.filter(Boolean).length; const rawChangedPixelCount = rawMask.filter(Boolean).length; const pixelArea = input.pixelSizeM * input.pixelSizeM;
  return { values, rawMask, cleanedMask, uncertaintyMask: values.map((value, i) => !Number.isFinite(value) || noDataMask[i] || cloudMask[i] || Math.abs(value - input.threshold) < input.threshold * 0.15), noDataMask, cloudMask, threshold: input.threshold, bandsUsed: input.bands.map((band) => band.name), meanChange: validValues.length ? validValues.reduce((a, b) => a + b, 0) / validValues.length : 0, maximumChange: validValues.length ? Math.max(...validValues) : 0, changedPixelCount, rawChangedPixelCount, removedNoisePixels: rawChangedPixelCount - changedPixelCount, changedPixelPercentage: total ? changedPixelCount / total * 100 : 0, affectedAreaM2: changedPixelCount * pixelArea, affectedAreaKm2: changedPixelCount * pixelArea / 1_000_000, minimumComponentSize };
}
