import { useState } from 'react';
import { Search, Satellite, ExternalLink, Check } from 'lucide-react';
import { searchCopernicusScenes, selectBestScenePair, type SatelliteCollection, type SatelliteScene } from '../services/satellite';

<<<<<<< HEAD
interface Props { onSelect?: (side: 'pre' | 'post', scene: SatelliteScene) => void; }

export function SatelliteSearchPanel({ onSelect }: Props) {
=======
interface Props { onSelect?: (side: 'pre' | 'post', scene: SatelliteScene) => void; onBestPair?: (pre?: SatelliteScene, post?: SatelliteScene) => void; }

export function SatelliteSearchPanel({ onSelect, onBestPair }: Props) {
>>>>>>> a8a4f96 (final update)
  const [collection, setCollection] = useState<SatelliteCollection>('sentinel-2-l2a');
  const [bbox, setBbox] = useState('86,26,87,27');
  const [preStart, setPreStart] = useState('2026-01-01'); const [preEnd, setPreEnd] = useState('2026-05-31');
  const [postStart, setPostStart] = useState('2026-06-01'); const [postEnd, setPostEnd] = useState('2026-10-06');
  const [maxCloud, setMaxCloud] = useState('30'); const [preScenes, setPreScenes] = useState<SatelliteScene[]>([]); const [postScenes, setPostScenes] = useState<SatelliteScene[]>([]);
  const [selectedPre, setSelectedPre] = useState<string>(); const [selectedPost, setSelectedPost] = useState<string>(); const [state, setState] = useState<'idle' | 'searching' | 'ready' | 'error'>('idle'); const [message, setMessage] = useState('');
  const runSearch = async () => { setState('searching'); setMessage(''); try { const values = bbox.split(',').map(Number); if (values.length !== 4 || values.some((value) => !Number.isFinite(value))) throw new Error('AOI must be minLon,minLat,maxLon,maxLat.'); const [pre, post] = await Promise.all([searchCopernicusScenes({ collection, bbox: values as [number, number, number, number], start: preStart, end: preEnd, maxCloud: Number(maxCloud), limit: 8 }), searchCopernicusScenes({ collection, bbox: values as [number, number, number, number], start: postStart, end: postEnd, maxCloud: Number(maxCloud), limit: 8 })]); setPreScenes(pre.scenes); setPostScenes(post.scenes); setSelectedPre(undefined); setSelectedPost(undefined); setMessage(`Pre-event: ${pre.scenes.length} scenes · Post-event: ${post.scenes.length} scenes · Catalogue queried ${new Date(post.searchedAt).toLocaleString()}`); setState('ready'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Satellite search failed.'); setState('error'); } };
  const choose = (side: 'pre' | 'post', scene: SatelliteScene) => { if (side === 'pre') setSelectedPre(scene.id); else setSelectedPost(scene.id); onSelect?.(side, scene); };
<<<<<<< HEAD
  const chooseBest = () => { const pair = selectBestScenePair(preScenes, postScenes); if (pair.pre) choose('pre', pair.pre); if (pair.post) choose('post', pair.post); setMessage(pair.reason); };
=======
  const chooseBest = () => { const pair = selectBestScenePair(preScenes, postScenes); if (pair.pre) choose('pre', pair.pre); if (pair.post) choose('post', pair.post); onBestPair?.(pair.pre, pair.post); setMessage(pair.reason); };
>>>>>>> a8a4f96 (final update)
  const sceneList = (side: 'pre' | 'post', scenes: SatelliteScene[]) => <div className="satellite-scenes">{scenes.map((scene) => { const selected = (side === 'pre' ? selectedPre : selectedPost) === scene.id; return <div className={`satellite-scene ${selected ? 'selected-scene' : ''}`} key={scene.id}><button className="scene-select" onClick={() => choose(side, scene)}>{selected ? <Check size={12} /> : <span />}</button><div><strong>{scene.title}</strong><span>Acquired {new Date(scene.datetime).toLocaleString()} · {scene.cloudCover === null ? 'Cloud N/A' : `${scene.cloudCover.toFixed(1)}% cloud`}</span><small>{scene.source} · {scene.id}</small></div>{scene.assets[0] && <a href={scene.assets[0].href} target="_blank" rel="noreferrer" title="Open catalogue asset"><ExternalLink size={13} /></a>}</div>; })}</div>;
  return <div className="satellite-panel"><div className="section-heading"><span className="eyebrow"><Satellite size={12} /> FETCH SATELLITE IMAGERY</span><span className={`mode-pill satellite-${state}`}>{state === 'searching' ? 'Searching' : state === 'ready' ? `${preScenes.length + postScenes.length} scenes` : state === 'error' ? 'Failed' : 'Ready'}</span></div><div className="satellite-form"><label>Collection<select value={collection} onChange={(e) => setCollection(e.target.value as SatelliteCollection)}><option value="sentinel-2-l2a">Sentinel-2 L2A optical</option><option value="sentinel-1-grd">Sentinel-1 GRD SAR</option></select></label><label>AOI bbox<input value={bbox} onChange={(e) => setBbox(e.target.value)} placeholder="minLon,minLat,maxLon,maxLat" /></label><div className="satellite-window"><b>Pre-event window</b><label>From<input type="date" value={preStart} onChange={(e) => setPreStart(e.target.value)} /></label><label>To<input type="date" value={preEnd} onChange={(e) => setPreEnd(e.target.value)} /></label></div><div className="satellite-window"><b>Post-event window</b><label>From<input type="date" value={postStart} onChange={(e) => setPostStart(e.target.value)} /></label><label>To<input type="date" value={postEnd} onChange={(e) => setPostEnd(e.target.value)} /></label></div><label>Max cloud %<input type="number" min="0" max="100" value={maxCloud} onChange={(e) => setMaxCloud(e.target.value)} /></label><button className="primary-button" onClick={runSearch} disabled={state === 'searching'}><Search size={13} /> Search official catalogue</button>{preScenes.length > 0 && postScenes.length > 0 && <button className="outline-button" onClick={chooseBest}><Check size={13} /> Find best pre/post pair</button>}</div>{message && <p className="satellite-message">{message}</p>}{preScenes.length > 0 && <><div className="satellite-subheading">PRE-EVENT SCENES {selectedPre && '· SELECTED'}</div>{sceneList('pre', preScenes)}</>}{postScenes.length > 0 && <><div className="satellite-subheading">POST-EVENT SCENES {selectedPost && '· SELECTED'}</div>{sceneList('post', postScenes)}</>}{selectedPre && selectedPost && <div className="satellite-ready">Pre/post pair selected. Asset download and raster processing require configured Copernicus credentials.</div>}</div>;
}
